databases:
  - name: algoforge-db
    plan: free
    databaseName: algoforge
    user: algoforge

services:
  - type: web
    name: algoforge-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: algoforge-db
          property: connectionString

      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: Jwt__Secret
        sync: false

      - key: Gemini__ApiKey
        sync: false

      - key: Resend__ApiKey
        sync: false

      - key: Resend__FromEmail
        value: onboarding@resend.dev

      - key: AppBaseUrl
        value: https://algoforge-api-b3b9.onrender.com

      - key: Jwt__Issuer
        value: AlgoForge.API

      - key: Jwt__Audience
        value: AlgoForge.Client

      - key: Judge0__BaseUrl
        value: https://ce.judge0.com/

      - key: Gemini__Model
        value: gemini-flash-latest
